#!/bin/sh

####
#   This file is edited to remove the gLite specific build requirements by Oscar Koeroo
####


###################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004. See
# http://www.eu-egee.org/partners/ for details on the copyright holders.
# 
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#
###################################################################



# Unfortunately the localinit target runs _after_ the init-autotools target,
# so we cannot do this from ant
version=`grep ^module.version project/version.properties | cut -d= -f2 | sed -e 's/[         ]//g'`
echo "AC_DEFUN([GLITE_MODULE_VERSION],[$version])" > project/module-version.m4

mkdir -p src/autogen
set -x
aclocal -I project
which libtoolize > /dev/null 2>&1
RC=$?
if [ ${RC} -eq 1 ]; then
    glibtoolize --force
else
    libtoolize --force
fi
autoheader
automake --foreign --add-missing --copy
autoconf
