#!/bin/sh

####
#   This file is edited to remove the gLite specific build requirements by Oscar Koeroo
#
# Log:
#   Applied Ryan's hint listed here: https://github.com/okoeroo/ssss/issues/2
####


###################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004. See
# http://www.eu-egee.org/partners/ for details on the copyright holders.
# 
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#
###################################################################


mkdir -p src/autogen
set -x
aclocal -I project

if [ ! -x "$(which libtoolize 2>/dev/null)" ]; then
    glibtoolize --force --copy
else
    libtoolize --force --copy
fi

autoheader
automake --add-missing --copy
autoconf
